server:
  port: 8087
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/surebank_db
    username: surebank_user
    password: hr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
logging:
  file:
    name: log/surebank.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
    
  level:
    '[com.bank.sure]': INFO
    
    
